dimensionedScalar oneSecond
(
    "oneSecond",
    dimensionSet(0,0,1,0,0,0,0),
    1.0
);

dimensionedScalar oneKelvin
(
    "oneSecond",
    dimensionSet(0,0,0,1,0,0,0),
    1.0
);

dimensionedScalar oneMeter
(
    "oneSecond",
    dimensionSet(0,1,0,0,0,0,0),
    1.0
);

dimensionedScalar minusOneKelvin
(
    "minusOneKelvin",
    dimensionSet(0,0,0,1,0,0,0),
    -1.0
);

dimensionedScalar zeroKelvin
(
    "zeroKelvin",
    dimensionSet(0,0,0,1,0,0,0),
    0.0
);

dimensionedScalar unitsBuoy
(
    "unitsBuoy",
    dimensionSet(1,-3,-1,0,0,0,0),
    1.0
);