{
    volScalarField boundedAlpha2 = min(max(alpha2, scalar(0)), scalar(1));
    volScalarField boundedAlpha3 = min(max(alpha3, scalar(0)), scalar(1));

    if (correctPhi)
    {
        rAU.ref() = 1.0/UEqn.A();
    }
    else
    {
        rAU = 1.0/UEqn.A();
    }

    surfaceScalarField rAUf("rAUf", fvc::interpolate(rAU()));
    volVectorField HbyA(constrainHbyA(rAU()*UEqn.H(), U, p_rgh));
    surfaceScalarField phiHbyA
    (
        "phiHbyA",
        fvc::flux(HbyA)
      + MRF.zeroFilter(fvc::interpolate(rho*rAU())*fvc::ddtCorr(U, phi, Uf))
    );
    MRF.makeRelative(phiHbyA);

    if (p_rgh.needReference())
    {
        fvc::makeRelative(phiHbyA, U);
        adjustPhi(phiHbyA, U, p_rgh);
        fvc::makeAbsolute(phiHbyA, U);
    }

    surfaceScalarField phig
    (
        (
            mixture.surfaceTensionForce()//*fvc::interpolate(topMetal)
//        - (vsfRho ? ghf*fvc::snGrad(rho) : ghf*fvc::snGrad(rho*(scalar(1.0) - beta*boundedAlpha2*(T - Tref))))
		- (vsfRho ? (rhofT ? ghf*fvc::snGrad((boundedAlpha1*rho1 + mixture.rhoBouss() - boundedAlpha2*rhoRef + mixture.rhoExp())*(scalar(1.0) - beta_2*boundedAlpha1*(T - Tref_2))) 
            : ghf*fvc::snGrad(rho*(scalar(1.0) - beta_2*boundedAlpha1*(T - Tref_2)))) 
            : ghf*fvc::snGrad(rho*(scalar(1.0) - beta*boundedAlpha2*(T - Tref))*(scalar(1.0) - beta_2*boundedAlpha1*(T - Tref_2))))       
        )*rAUf*mesh.magSf()
    );

    phiHbyA += phig;

    // Update the pressure BCs to ensure flux consistency
    constrainPressure(p_rgh, U, phiHbyA, rAUf, MRF);

    while (pimple.correctNonOrthogonal())
    {
        fvScalarMatrix p_rghEqn
        (
            fvm::laplacian(rAUf, p_rgh) == fvc::div(phiHbyA)
//            - dmdtRelaxPressure.value()*Su
        );

        p_rghEqn.setReference(pRefCell, getRefCellValue(p_rgh, pRefCell));

        p_rghEqn.solve(mesh.solver(p_rgh.select(pimple.finalInnerIter())));


        if (pimple.finalNonOrthogonalIter())
        {
            phi = phiHbyA - p_rghEqn.flux();

            p_rgh.relax();

            U = HbyA + rAU()*fvc::reconstruct((phig - p_rghEqn.flux())/rAUf);
            U.correctBoundaryConditions();
            fvOptions.correct(U);
        }
    }

    #include "continuityErrs.H"

    // Correct Uf if the mesh is moving
    fvc::correctUf(Uf, U, phi);

    // Make the fluxes relative to the mesh motion
    fvc::makeRelative(phi, U);


    p == p_rgh + rho*gh;

    if (p_rgh.needReference())
    {
        p += dimensionedScalar
        (
            "p",
            p.dimensions(),
            pRefValue - getRefCellValue(p, pRefCell)
        );
        p_rgh = p - rho*gh;
    }

    if (!correctPhi)
    {
        rAU.clear();
    }

}
